version: 2

jobs:
  build:
    macos:
      xcode: "9.3.0"
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    shell: /bin/bash --login -eo pipefail

    steps:
      - checkout
      - restore_cache:
          key: libvlc-{{ checksum "compileAndBuildVLCKit.sh" }}
      - run:
          name: Build VLCKit
          command: |
            rake build:vlckit:ios
      - save_cache:
          key: libvlc-{{ checksum "compileAndBuildVLCKit.sh" }}
          paths:
            - build
            - libvlc
            - Resources
      - run:
          name: Run Tests
          command: |
            rake test:ios

